# Generated by Django 5.0.7 on 2024-09-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_employee_is_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='pause_time',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='paused',
        ),
    ]
