# Generated by Django 5.0.7 on 2024-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_remove_worksession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
