# Generated by Django 5.0.7 on 2024-10-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_employee_is_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_first_login',
        ),
    ]
