# Generated by Django 5.0.7 on 2024-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_remove_employee_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password_reset_used',
            field=models.BooleanField(default=False),
        ),
    ]
