# Generated by Django 5.0.7 on 2024-10-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_rename_password_reset_used_employee_has_reset_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='has_reset_password',
            new_name='password_reset_used',
        ),
    ]
